# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevSheet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevSheet

  # Architecture
  pod 'ReactorKit'

  # Rx
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'

  # Toast
  pod 'Loaf'

  # Layout
  pod 'SnapKit'

  # Dependency Injection
  pod 'Swinject'

  # Lint
  pod 'SwiftLint'

  target 'DevSheetTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'Quick'
    pod 'Nimble'
  end

  target 'DevSheetUITests' do
    # Pods for testing
  end

end
